- // MIR for `move_up_mut` before Alias
+ // MIR for `move_up_mut` after Alias
  
  fn move_up_mut(_1: &mut i32, _2: &mut i32) -> i32 {
      debug x => _1;                       // in scope 0 at $DIR/move_up_mut.rs:3:16: 3:17
      debug y => _2;                       // in scope 0 at $DIR/move_up_mut.rs:3:29: 3:30
      let mut _0: i32;                     // return place in scope 0 at $DIR/move_up_mut.rs:3:45: 3:48
      let mut _3: !;                       // in scope 0 at $DIR/move_up_mut.rs:3:49: 7:2
  
      bb0: {
          (*_1) = const 42_i32;            // scope 0 at $DIR/move_up_mut.rs:4:5: 4:12
          (*_2) = const 7_i32;             // scope 0 at $DIR/move_up_mut.rs:5:5: 5:11
          _0 = (*_1);                      // scope 0 at $DIR/move_up_mut.rs:6:12: 6:14
          return;                          // scope 0 at $DIR/move_up_mut.rs:7:2: 7:2
      }
  }
  
